image: maven:3.3.9-jdk-8
cache:
  paths:
    - .m2/repository
before_script:
  - apt-get update -y && apt-get upgrade -y
    
build:
  script:
    - mvn package -B
  artifacts:
    name: "inactivelockette"
    paths:
      - ./target/inactivelockette*.jar
