main: gvlfm78.plugin.InactiveLockette.ILMain
name: InactiveLockette
version: 3.1.2
author: gvlfm78
description: Allows opening of lockette locks after a set amount of time

softdepend: [Vault,Lockette,LockettePro]

commands:
  InactiveLockette:
    description: InactiveLockette's main command
    aliases: il

permissions:
  inactivelockette.*:
    description: Gives access to all inactivelockette permissions
    default: op
  children:
    inactivelockette.admin: true
    inactivelockette.player: true
  inactivelockette.admin:
    description: Allows use of the /inactivelockette command
    default: op
  inactivelockette.player:
    description: Allows players to open inactive locks
    default: op