# InactiveLockette Plugin by gvlfm78
# Bukkit Page: http://dev.bukkit.org/bukkit-plugins/inactive-lockette
# Spigot Page: https://www.spigotmc.org/resources/inactive-lockette.25644
# GitHub Page: https://github.com/gvlfm78/InactiveLockette

# Language for the locale file - you must delete the locale and then
# do /il reload for them to be re-created with the language set here
# If you wish to contribute translations take the locale file, edit the
# strings and send them over to me. I'll put them in the next version.
# Currently available languages: enGB, itIT, frFR
language: enGB

# After how many days the lock should be openable
# You can set this to -1 if you want the locks to always be openable
daysOfInactivity: 30

# If the plugin should empty the opened containers
clearItems: false

# If the plugin should show how long the owner of the lock has been inactive for
onClickDisplayDays: true

# If the plugin should show how many days until the lock can be opened
onClickDisplayDaysToWait: true

# If the plugin should broadcast a message with the coordinates and block type of
# the opened container for other players to hunt it down
broadcast: true

# If the plugin should check if the player has the permission
# inactivelockette.player before allowing them to open the lock
permissionToOpenLocks: true

# Only allow user to break lock if they are the owner of the WorldGuard region the block is in
breakLockIfRegionOwner: false

# Only allow user to break lock if they have WorldGuard BUILD permission for the region the block is in
breakLockIfCanBuild: false

# If the plugin should use economy
useEconomy: false

# Cost the player pays every time they break open a container if economy is enabled
cost: 500.0

# List of people whose locks cannot be opened
# Example list: [gvlfm78,8cd16032-c3d5-35a0-8c41-a9fd41178779,Best_Player]
list: []

# Whether to check only first name on sign or, if first name inactive,
# check all the names including [More Users] signs and remove inactive owners,
# keeping the same order on the sign
onlyCheckFirstName: false

# If the plugin should check for updates
checkForUpdates: true

###########################################################
#####################OTHER SETTINGS########################
## DO NOT CHANGE THIS UNLESS YOU KNOW WHAT YOU'RE DOING ###
## IF IN DOUBT, NO, YOU DON'T KNOW WHAT YOU'RE DOING ######
###########################################################
config-version: 2